org: hospace
app: mashup-node

service: nest-graphql-mercurius-fastify

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          path: graphql
          method: POST
