name: Deploy serverless application

on:
  push:
    branches:
      - main
      - feat/cd

jobs:
  validate:
    name: Validate and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Lint code
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            dist/
            node_modules/
            package.json
            yarn.lock
            serverless.yml
            prisma/
            src/
          retention-days: 1

  deploy:
    name: Deploy to AWS Lambda
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Install Serverless Framework
        run: npm install -g serverless@3.38.0

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Run Prisma migrations
        run: npx prisma migrate deploy 2>&1 | grep -v 'Datasource "db":' | grep -v 'PostgreSQL database'
        env:
          DB_URL: ${{ secrets.DB_URL }}

      - name: Create .env file
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env

      - name: Configure serverless credentials
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy serverless app
        run: npx serverless deploy 2>&1 | grep -v 'endpoint:'
